<script type="text/javascript">

    $(function(){       
        $('#message_body').wysiwyg();
        $('#note_text').wysiwyg();

    });

    function sendMessage()
    {
        if($('#frm-contact').valid())
        {
            $.ajax({
                type: "post",
                url:  $('#frm-contact').attr('action'),
                data: $('#frm-contact').serialize(),
                success: function(msg){
                    $("#frm-contact").html("Message sent succefully.");
                }
            });
        }

       return false;
    }

    function saveProfile(profileId)
    {
        $.ajax({
                type: "post",
                url:  "<?php echo $this->baseUrl().'/user/message/save-profile/profile-id/' ?>" + profileId,
                success: function(msg){
                    $("#frm-apply").html("Message sent succefully.");
                }
            });
    }

    function saveEmployerNote()
    {
        if($('#frm-note').valid())
        {
            $.ajax({
                type: "post",
                url:  $('#frm-note').attr('action'),
                data: $('#frm-note').serialize(),
                success: function(msg){
                    $("#frm-note").html("Note saved succefully.");
                }
            });
        }

       return false;
    }

</script>

    <?php if( count($this->internProfileInfo) > 0 )
    { ?>

<h1 class="intern_header">
            <?php echo ucwords($this->internProfileInfo['userEducations'][0]->major);  ?> Major
            </h1>
        	<!-- start of left panel -->

            <div class="panel_left">

                    <div class="gray_header_box">
                    	<div class="gray_header_box_top"><p class="gray_heading"><?php echo $this->internProfileInfo['internInfo'][0]->profile_title . ', ' .$this->internProfileInfo['internInfo'][0]->location_name; ?></p></div>
                        <div class="gray_header_box_middle">

                        <div class="profile_summary" <?php if($this->accessLevel == 'guest') echo "style='border:0;'"; ?> >

                            <div class="availability">
                            <span class="darkgray small"><strong>Availability</strong></span>
                            <br />
                            <span class="gray small"><?php echo $this->internProfileInfo['internInfo'][0]->title; ?></span>
                            <br />
                            <span class="gray small">
                                <?php
                                    $cnt = 0;
                                    sort($this->internProfileInfo['userAvailabilities']);
                                    foreach ($this->internProfileInfo['userAvailabilities'] as $availability) {
                                        if( $availability->availability_id == 1) {
                                                echo $availability->title;
                                                break;
                                        }
                                        else{
                                            if($cnt>0) echo ', ';
                                            echo $availability->title;
                                            $cnt++;
                                        }
                                    }
                                    if($cnt > 0)
                                        echo ' only';
                                ?>
                            </span>
                            </div>

                        <div class="day_grid">
                        <table border="0" cellpadding="0" cellspacing="0" class="spider">
                            <tr class="smallheader">
                                <td></td><td>M</td><td>T</td><td>W</td><td>Th</td><td>F</td><td>S</td><td>Su</td>
                            </tr>
                            <?php

                            $sids = array();

                            foreach ($this->internProfileInfo['userSchedules'] as $value) {
                                $sids[] = $value->schedule_id;
                            }

                                $cnt = 0;
                                foreach ($this->schedules as $schedule) {
                                    
                                    if($cnt == 0)
                                         $daytime = "Morning" ;
                                    else if ($cnt == 7)
                                         $daytime = "Afternoon";
                                    else if ($cnt == 14)
                                         $daytime = "Evening";
                                    if(@in_array($schedule->schedule_id, $sids))
                                        $wsc = 'view-select-sedule';
                                    else
                                        $wsc = 'view-select-sedule-deactive';
                                    if($cnt == 0 || $cnt == 7 || $cnt == 14)echo '<tr><td class="smallfont">'.$daytime.'</td>';
                                    echo "<td class='$wsc'>
                                        <a class='schanchor' href='javascript:void(0)'>
                                        </a></td>";
                                    if($cnt == 6 || $cnt == 13 || $cnt == 20)  echo '</tr>';    $cnt++;
                                }
                            ?>
                        </table>
                        </div>

                       <?php if ($this->accessLevel != 'guest'): ?>

                                <div class="profile_links">
                                    <ul>
                                <?php
                                    if ($this->internProfileInfo['internInfo'][0]->resume_file_name != '') {
                                        echo "<li><a href='{$this->internProfileInfo['internInfo'][0]->resume_file_name}'><img src='{$this->baseUrl()}/public/images/profile_resume.png' alt='Resume' /></a></li>";
                                    }
                                    if ($this->internProfileInfo['internInfo'][0]->linkedin_url != '') {
                                        echo "<li><a href='{$this->internProfileInfo['internInfo'][0]->linkedin_url}'><img src='{$this->baseUrl()}/public/images/profile_linkedin.png' alt='linkedin' /></a></li>";
                                    }
                                    if ($this->internProfileInfo['internInfo'][0]->twitter_url != '') {
                                        echo "<li><a href='{$this->internProfileInfo['internInfo'][0]->twitter_url}'><img src='{$this->baseUrl()}/public/images/profile_twitter.png' alt='twitter' /></a></li>";
                                    }
                                    if ($this->internProfileInfo['internInfo'][0]->personal_url != '') {
                                        echo "<li><a href='{$this->internProfileInfo['internInfo'][0]->personal_url}'><img src='{$this->baseUrl()}/public/images/profile_web.png' alt='web' /></a></li>";
                                    }
                                ?>
                                    </ul>
                                </div>
                                    <?php endif;
                                    ?>
                        </div>


                        <div class="profile_picture">
                            <?php                              
                            if($this->accessLevel != 'guest') : ?>
                            <img src="<?php echo $this->baseUrl().'/public/uploads/interns/thumbs/'. $this->internProfileInfo['internInfo'][0]->photo_file_name ?>" alt="Profile picture of demo" class="padd10"/>
                           <?php endif; ?>
                           </div>


                        </div>
                        <div class="gray_header_box_bottom"></div>
                    </div>


                    <div class="clear"></div>

                    <br />

                    <span class="padd10 darkgray">
                    <?php echo $this->internProfileInfo['internInfo'][0]->about_me; ?>
                    </span>

                    <br />
                    <br />                 


                    <div class="left wid300">
                    <img src='<?php echo $this->baseUrl().'/public/images/icon_star.png'?>' alt='star' />&nbsp;<span class="darkgray"><b>Interests</b></span><br />
                    <ul class="little_star_list">
                        <?php
                        foreach ($this->internProfileInfo['userInterests'] as $industry) {
                                    echo "<li>".$industry->industry_name . '</li>';
                            }
                        ?>
                    </ul>
                    <div class="clear"></div>
                    <br />
                    <br />
                    <img src='<?php echo $this->baseUrl().'/public/images/icon_star.png' ?>' alt='star' />&nbsp;<span class="darkgray"><b>Education</b></span><br />
                    <ul class="little_star_list">
                        <li><?php echo $this->internProfileInfo['userEducations'][0]->school_name .',';
                            echo $this->internProfileInfo['userEducations'][0]->education_title .',';
                            echo $this->internProfileInfo['userEducations'][0]->graduation_year; ?>(expected)</li>
                    </ul>
                   </div>

                   <div class="left wid300">
                    <img src='<?php echo $this->baseUrl().'/public/images/icon_star.png' ?>' alt='star' />&nbsp;<span class="darkgray"><b>Skills</b></span><br />
                    <ul class="little_star_list">
                       <?php
                       foreach ($this->internProfileInfo['userSkills'] as $skill) {
                    echo "<li>".$skill->skill_name . '</li>';
            }
                       ?>
                    </ul>
                   </div>

                   <div class="clear"></div>
                   <br />
                   <br />
                   <?php if ($this->accessLevel != 'guest') : ?>
                   <div class="references">
                       <br />

                       <img src='<?php echo $this->baseUrl().'/public/images/icon_star.png' ?>' alt='star' />&nbsp;<span class="darkgray"><b> Reference from Abe Graham, Pinwheel Media, NY</b></span><br />

                       <span class="padd10 darkgray">
                       Stacey is great!. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
                       </span>
                       <br />
                       <br />
                       <span class="padd10 darkgray">
                       A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.
                       </span>
                       <br />
                       <br />
                       <span class="padd10 darkgray">
                       Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. The Big Oxmox advised her not to do so, because there were thousands of bad Commas.
                       </span>

                       <div class="clear"></div>
                       <br />
                   <br />

                   </div>
                   <?php else : ?>
                   3 referencees viewable on log in
                   <?php endif; ?>

              </div>
              <!-- end of left panel -->

              <!-- start of right panel -->
<div class="panel_right">
 <?php  if(!strcmp($this->accessLevel , 'employer') )
 {
 ?>   

                <?php if($this->hasProfile) { ?>
                <!-- start of right panel contact box -->
                <div class="contact_box">
                    <div class="contact_box_top">
                            <div class="left_heading"> <img src="<?php echo $this->baseUrl().'/public/images/icon_star.png'?>" alt="Star" /> &nbsp;Contact</div>
                            <div class="green_links right"><a href="javascript:void(0)" onclick="saveProfile(<?php echo $this->internProfileInfo['internInfo'][0]->user_id; ?>)"> <img src="<?php echo $this->baseUrl().'/public/images/save_intern.png'?>" alt="save intern" align="middle" /></a></div>
                    </div>

                    <div class="contact_box_middle">

                            <div class="contact_box_content">

                                <form id="frm-contact" action="<?php echo $this->baseUrl().'/user/message/send-message'; ?>" onsubmit="return sendMessage();">

                                    <input type="hidden" name="from" value="<?php echo $this->empployerInfo['empInfo'][0]->user_id; ?>" />
                                    <input type="hidden" name="to" value="<?php echo $this->internProfileInfo['internInfo'][0]->user_id; ?>" />

                                    <label class="smalllabel darkgray lh22">From</label>
                                    <span class="green left lh22"><b><?php  echo $this->empployerInfo['empInfo'][0]->company_name; ?></b></span>
                                    <div class="clear"></div>
                                    <label class="smalllabel darkgray lh22">Subject</label>
                                    <span class="left lh22"><input type="text" class="required input" name="message_subject" value="a great job for you"/></span>
                                    <div class="clear"></div>
                                    <label class="smalllabel darkgray lh22">Link to job</label>
                                    <span class="left lh22"><select name="job_id" class="select wid235">
                                             <?php
                                            foreach ($this->employerActiveJobs as $job) {
                                                echo "<option value='{$job->job_id}'>{$job->job_title}</option>";
                                            }
    ?>
                                        </select></span>
                                    <div class="clear"></div>
                                    <textarea name="message_body" id="message_body" class="required bigtxt wid300 right">Write message here...</textarea>
                                    <br />
                                    <span class="darkgray margin10"><b><input type="checkbox" checked name="save_profile">&nbsp; Save Profile</b></span>
                                    <br />
                                    <input type="submit" class="send_button left margin10" />
                                </form>
                            </div>

                    </div>

                    <div class="contact_box_bottom"></div>

                </div>
                <!-- end of right panel contact box -->


                <!-- start of right panel small box -->
                <div class="right_box">
                    <div class="right_box_top">
                            <div class="left_heading"> <img src="<?php echo $this->baseUrl().'/public/images/icon_star.png'?>" alt="Star" /> &nbsp;My Notes <span class="darkgray smallfont">(Only visible to you)</span></div>

                    </div>

                    <div class="right_box_middle">

                            <div class="right_box_content">
                                 <form id="frm-note" action="<?php echo $this->baseUrl().'/user/message/save-employer-note'; ?>" onsubmit="return saveEmployerNote();">
                                     <input type="hidden" name="employer_id" value="<?php echo $this->empployerInfo['empInfo'][0]->user_id; ?>" />
                                     <input type="hidden" name="intern_id" value="<?php echo $this->internProfileInfo['internInfo'][0]->user_id; ?>"  />

                                    <textarea name="note_text" id="note_text" class="required bigtxt">Save note here... </textarea>
                                <br />
                                <input type="submit" class="save_button" />
                                 </form>
                            </div>

                    </div>

                    <div class="right_box_bottom"></div>

                </div>
                <!-- end of right panel small box -->

                <p class="green margin10"><b>FLAG THIS PAGE FOR OFFENSIVE CONTENT</b></p>

                <?php } else { ?>
                <h4>You need to create employer profile.</h4>

                <?php } ?>
              

              <?php } else if($this->accessLevel == 'guest'): ?>

                <div class="registration_right_top "></div>

                <div class="right_box_middle">
                    <div class="right_box_content">
                        <a href="<?php echo $this->baseUrl().'/registration/account/login' ?>"><img alt="" src="<?php echo $this->baseUrl().'/public/images/button_login.png' ?>" /></a><span class="gray_heading">or</span><span class="gray_heading"></span>
                        <a href="<?php echo $this->baseUrl().'/registration/account/post-job' ?>"><img alt="" src="<?php echo $this->baseUrl().'/public/images/button_register.png' ?>" /></a>
                    </div>
                </div>
                <div class="right_box_bottom"></div>

                <?php endif; ?>
            </div>

              <!-- end of right panel -->

<?php }

else { ?>
<h1 class="intern_header">
           Invalid Profile Search.
</h1>   

<?php
}
?>








