<script type="text/javascript">
    function deleteJobSavedSearch(searchId)
    {
        $('#job-save-search').html('<img style="padding-left:150px;" src="<?php echo $this->baseUrl().'/public/images/loading.gif'?>" />');

        $.ajax({
            url: '<?php echo $this->baseUrl().'/search/job/delete-job-search/search-id/'?>'+searchId ,
            success: function(response){
                $('#job-save-search').html(response);
            }
        });
    }
</script>

             <?php
                    if(!$this->hasProfile)
                            echo '<h1 class="intern_header">Welcome! Complete your <a href="'. $this->baseUrl().'/user/profile/create-intern-profile' .'"><span class="green">Profile</span></a> today.</h1>';
                ?>
        	<!-- start of left panel -->

            <div class="panel_left">

                    <!-- start featured intern box -->

                    <div class="featured_box">
                        <div class="featured_box_top">
                            <div class="left_heading"> <img src="<?php echo $this->baseUrl().'/public/images/icon_star.png'?>" alt="Star" /> &nbsp;INBOX</div>

                            <div class="green_links right"><a href="<?php echo $this->baseUrl().'/user/message/inbox' ?>">ALL Message ></a></div>
                        </div>

                        <div class="featured_box_middle">


                       <?php
               if(count($this->allMessages) > 0)
   {

       foreach ($this->allMessages as $message) {
          if(array_key_exists('company_name', $message))
            $name = $message->company_name;
          else
              $name = $message->first_name .' '.$message->last_name;

          if($message->parent_message_id != 0) $re = "Re: "; else $re = '';

          if($message->status == 'Unread')
                $class = "unread";
          else
                $class = "read";
            ?>
        <ul class="inbox wid590">
            <li class="<?php echo $class; ?>" onclick="javascrip:document.location='<?php echo $this->baseUrl().'/user/message/inbox' ?>'">
                <ul>
                    <li class="msg_from">
                        <?php echo $name ?> 
                    </li>
                    <li class="msg_subj">
                        <?php echo $re. $message->message_subject; ?>
                    </li>
                    <li class="inbox_time">
                        <?php echo date("H:iA m/d/y", strtotime($message->sent_on)); ?>
                    </li>
                </ul>
            </li>
        </ul>
        <?php
       }
   }
     else {
        echo "<h3 class='margin20'>Inbox is Empty.!</h3>";
    }
        ?>



                        </div>

                        <div class="featured_box_bottom">
                        </div>


                        <div class="clear"></div>
                        <br />

                             <!--============================================================= -->

                                        <div class="featured_box_top">
            <div class="left_heading"> <img src="<?php echo $this->baseUrl() . '/public/images/icon_star.png' ?>" alt="Star" /> &nbsp;My Saved Searches</div>


        </div>

        <div id="job-save-search" class="featured_box_middle">

            <ul class="inbox wid590">
                <?php foreach($this->saveSearch as $value) : ?>
                <li class="msg_from"><a href="<?php echo $this->baseUrl().'/search/job/job-search-results/?'. $value->search_url; ?>"><?php echo $value->search_name; ?></a></li>
                <li class="msg_subj">3 new matches <?php echo "<a href='javascript:void(0)' onclick='deleteJobSavedSearch({$value->user_saved_search_id})'><img alt='delete' src='{$this->baseUrl()}/public/images/delete.png'></a>" ?></li>
                <?php endforeach; ?>
            </ul>

        </div>

        <div class="featured_box_bottom">
        </div>


        <div class="clear"></div>
        <br />

        <!--============================================================= -->


                        <div class="featured_box_top">
                            <div class="left_heading"> <img src="<?php echo $this->baseUrl().'/public/images/icon_star.png'?>" alt="Star" /> &nbsp;Browse Jobs</div>
                        </div>

                        <div class="featured_box_middle">

                             <ul class="keywords">
                            <li class="keywords_header">By Skills</li>
                            <?php
                                foreach ($this->skills as $value) {
                                    echo "<li><a href='{$this->baseUrl()}/search/job/job-search-results/?skill={$value->skill_name}'>". ucwords($value->skill_name)."</a></li>";
                                }
                            ?>
                        </ul>

                        <ul class="keywords">
                        	<li class="keywords_header">By Industry</li>
                                <?php
                                 foreach ($this->industry as $value) {
                                    echo "<li><a href='{$this->baseUrl()}/search/job/job-search-results/?industry/{$value->industry_name}'>".ucwords($value->industry_name)."</a></li>";
                                }
                            ?>
                        </ul>

                        <ul class="keywords">
                        	<li class="keywords_header">By Availability</li>
                           <?php
                                foreach ($this->availablity as $value) {
                                    echo "<li><a href='{$this->baseUrl()}/search/job/job-search-results/?seasons={$value->title}'>".ucwords($value->title)."</a></li>";
                                }
                            ?>
                        </ul>

                        <ul class="keywords noborder">
                        	<li class="keywords_header">By Location</li>
                            <?php
                                 foreach ($this->location as $value) {
                                    echo "<li><a href='{$this->baseUrl()}/search/job/job-search-results/?location_name={$value->location_name}'>".ucwords($value->location_name)."</a></li>";
                                }
                            ?>
                        </ul>

                        </div>

                        <div class="featured_box_bottom">
                        </div>



                    </div>


                    <!-- end featured intern box -->

              </div>
              <!-- end of left panel -->

              <!-- start of right panel -->

<div class="panel_right">




                <!-- start of right panel small box -->
                <div class="right_box">
                    <div class="right_box_top">
                            <div class="left_heading"> <img src="<?php echo $this->baseUrl().'/public/images/icon_star.png'?>" alt="Star" /> &nbsp;Saved Jobs</div>

                            <div class="green_links right"><a href="">ALL ACTIVE JOBS ></a></div>
                    </div>

                    <div class="right_box_middle">

                            <div class="right_box_content">

                                <ul class="folder_list">
                                    <?php  foreach ($this->savedJobs as $value) : ?>
                                    <li> <a href="<?php echo $this->baseUrl().'/employer/job/job-details/job-id/'. $value->job_id; ?>"><b><?php echo $value->job_title; ?> at <?php echo $value->company_name ?></b></a>
                                         <br />
                                         <?php if (!empty ($value->sent_on) || !empty ($value->note_text)): ?>
                                            <img src="<?php echo $this->baseUrl().'/public/images/sticky.png'?>" alt="note" /> <span class="darkgray"> <?php !empty ($value->sent_on) ? print date('d/m', strtotime($value->sent_on)) : ''; ?> <?php echo $value->note_text; ?></span>
                                            <?php endif; ?>
                                        </li>
                                    <?php endforeach; ?>
                                                              
                                </ul>

                            </div>

                    </div>

                    <div class="right_box_bottom"></div>

                </div>
                <!-- end of right panel small box -->


                <!-- start of right panel small box -->
                <div class="right_box">
                    <div class="right_box_top">
                            <div class="left_heading"> <img src="<?php echo $this->baseUrl().'/public/images/icon_star.png'?>" alt="Star" /> &nbsp;My Stats</div>

                            <div class="green_links right"><a href="<?php echo $this->baseUrl().'/user/profile/my-profile/' ?>">View </a> / <a href="<?php echo $this->baseUrl().'/user/profile/edit-my-profile' ?>"> Edit Profile ></a></div>
                    </div>

                    <div class="right_box_middle">

                            <div class="right_box_content">

        <b>Profile appeared in searches : </b> <?php isset ($this->internStats[0]->appeared_in_search) ? print $this->internStats[0]->appeared_in_search : print 0 ; ?> <br />
        <p><b>Profile Clicked : </b> <?php isset ($this->internStats[0]->profile_clicked) ? print $this->internStats[0]->profile_clicked : print 0 ; ?> <br />
        <p><b>Message Received : </b> <?php isset ($this->total_message) ? print $this->total_message : print 0; ?> <br />

                <br />

            <h3>How to improve your stats</h3>


                            </div>

                    </div>

                    <div class="right_box_bottom"></div>

                </div>
                <!-- end of right panel small box -->


              </div>

              <!-- end of right panel -->





