<script type="text/javascript">

    $(function(){
         $('#message_body').wysiwyg();
         $('#note_text').wysiwyg();
    });

    function sendMessage()
    {
        if($('#frm-apply').valid())
        {
            $.ajax({
                type: "post",
                url:  $('#frm-apply').attr('action'),
                data: $('#frm-apply').serialize(),
                success: function(msg){
                    $("#frm-apply").html("Message sent succefully.");
                }
            });
        }

       return false;
    }

    function saveJob(jobId)
    {
        $.ajax({
                type: "post",
                url:  "<?php echo $this->baseUrl().'/user/message/save-job/job-id/' ?>" + jobId,
                success: function(msg){
                    $("#frm-apply").html("Message sent succefully.");
                }
            });
    }

    function saveUserNote()
    {
        if($('#frm-note').valid())
        {
            $.ajax({
                type: "post",
                url:  $('#frm-note').attr('action'),
                data: $('#frm-note').serialize(),
                success: function(msg){
                    $("#frm-note").html("Note saved succefully.");
                }
            });
        }

       return false;
    }

</script>
<?php
    if( count($this->jobDetails) > 0 )
    {
        ?>
            <h1 class="intern_header">
            <?php echo ucwords($this->jobDetails['jobInfo'][0]->job_title);  ?>
            </h1>
        	<!-- start of left panel -->

            <div class="panel_left">

                    <div class="gray_header_box">
                    	<div class="gray_header_box_top"><p class="gray_heading"><span class="green"><?php echo ucwords($this->jobDetails['jobInfo'][0]->company_name);  ?></span>, <?php echo ucwords($this->jobDetails['jobInfo'][0]->location_name);  ?></p></div>
                        <div class="gray_header_box_middle">

                        <div class="profile_summary">

                            <div class="availability">
                            <span class="darkgray small"><strong>Schedule</strong></span>
                            <br />
                            <span class="gray small"><?php echo $this->jobDetails['jobInfo'][0]->title ?></span>
                            <br />
                            <span class="gray small">
                                 <?php
                                    $cnt = 0;
                                    sort($this->jobDetails['jobPeriods']);
                                    foreach ($this->jobDetails['jobPeriods'] as $availability) {
                                        if( $availability->period_id == 1) {
                                                echo $availability->title;
                                                break;
                                        }
                                        else{
                                            if($cnt>0) echo ', ';
                                            echo $availability->title;
                                            $cnt++;
                                        }
                                    }
                                    if($cnt > 0)
                                        echo ' only';
                                ?>

                            </span>
                            </div>

                    <div class="day_grid">
                        <table border="0" cellpadding="0" cellspacing="0" class="spider">
                            <tr class="smallheader">
                                <td></td><td>M</td><td>T</td><td>W</td><td>Th</td><td>F</td><td>S</td><td>Su</td>
                            </tr>
                            <?php

                                $sids = array();
                                
                                foreach ($this->jobDetails['jobSchedules'] as $value) {
                                    $sids[] = $value->schedule_id;
                                }

                                $cnt = 0;
                                foreach ($this->schedules as $schedule) {

                                    if($cnt == 0)
                                         $daytime = "Morning" ;
                                    else if ($cnt == 7)
                                         $daytime = "Afternoon";
                                    else if ($cnt == 14)
                                         $daytime = "Evening";
                                    if(@in_array($schedule->schedule_id, $sids))
                                        $wsc = 'view-select-sedule';
                                    else
                                        $wsc = 'view-select-sedule-deactive';
                                    if($cnt == 0 || $cnt == 7 || $cnt == 14)echo '<tr><td class="smallfont">'.$daytime.'</td>';
                                    echo "<td class='$wsc'>
                                        <a class='schanchor' href='javascript:void(0)'>
                                        </a></td>";
                                    if($cnt == 6 || $cnt == 13 || $cnt == 20)  echo '</tr>';    $cnt++;
                                }
                            ?>
                        </table>
                        </div>

                            <div class="clear"></div>
                            <span class="gray small"><?php echo $this->jobDetails['jobInfo'][0]->industry_name; ?></span>
                            <br />
                            <span class="gray small">Minimum Education: <?php echo $this->jobDetails['jobEducation'][0]->education_title; ?></span>


                        </div>


                        <div class="profile_picture">
                           <img src="<?php echo $this->baseUrl().'/public/uploads/employers/thumbs/'. $this->jobDetails['jobCompany'][0]->logo_file ?>" alt="logo of demo company" class="padd10"/>
                        </div>


                        </div>
                        <div class="gray_header_box_bottom"></div>
                    </div>


                    <div class="clear"></div>

                    <br />

                    <span class="padd10 darkgray">Reports to: <b><?php echo $this->jobDetails['jobInfo'][0]->reports_to; ?></b>
                    </span>
                    <br />
                    <br />

                    <img src='<?php echo $this->baseUrl().'/public/images/icon_star.png' ?>' alt='star' />&nbsp;<span class="darkgray"><b>Responsibilities</b></span><br />
                    <?php echo $this->jobDetails['jobInfo'][0]->responsibilites ?>
                    <br />                    

                    <div class="clear"></div>
                    <br />
                    <br />


                    <img src='<?php echo $this->baseUrl().'/public/images/icon_star.png' ?>' alt='star' />&nbsp;<span class="darkgray"><b>Qualifications</b></span><br />
                    <?php echo $this->jobDetails['jobInfo'][0]->qualifications ?>
                    <br />                   

                    <div class="clear"></div>

                    <br />
                    <br />


                    <img src='<?php echo $this->baseUrl().'/public/images/icon_star.png' ?>' alt='star' />&nbsp;<span class="darkgray"><b>Tasks / Skills</b></span><br />
                    &nbsp; <br />
                    <ul class="little_star_list">
                         <?php
                             foreach ($this->jobDetails['jobSkills'] as $skill) { ?>                                 
                                <?php echo "<li>{$skill->skill_name}</li>";
                             }
                         ?>
                    </ul>

                    <div class="clear"></div>

                    <br />
                    <br />

                    <img src='<?php echo $this->baseUrl().'/public/images/icon_star.png' ?>' alt='star' />&nbsp;<span class="darkgray"><b>PAY</b></span><br />
                    <?php echo $this->jobDetails['jobInfo'][0]->pay_type;
                            if($this->jobDetails['jobInfo'][0]->pay_type == 'hourly')
                                    echo ", \${$this->jobDetails['jobInfo'][0]->pay_amount}/hr"
                            ?>
                    <br />

                    <br />
                    <br />

              </div>
              <!-- end of left panel -->

              <!-- start of right panel -->

              <?php if($this->accessLevel == 'intern') { ?>

              <div class="panel_right">

                <?php if($this->hasProfile) { ?>

                <!-- start of right panel contact box -->
                <div class="contact_box">
                    <div class="contact_box_top">
                            <div class="left_heading"> <img src="<?php echo $this->baseUrl().'/public/images/icon_star.png'?>" alt="Star" /> &nbsp;Apply to Job</div>
                            <div class="green_links right"><a href="javascript:void(0)" onclick="saveJob(<?php echo $this->jobDetails['jobInfo'][0]->job_id; ?>)"> <img src="<?php echo $this->baseUrl().'/public/images/save_job.png'?>" alt="save intern" align="middle" /></a></div>
                    </div>

                    <div class="contact_box_middle">

                            <div class="contact_box_content">
                                <form id="frm-apply" action="<?php echo $this->baseUrl().'/user/message/send-message'; ?>" onsubmit="return sendMessage();">

                                     <input type="hidden" name="mail" value="1" />
                                    <input type="hidden" name="apply" value="1"/>
                                    <input type="hidden" name="job_title" value="<?php echo ucwords($this->jobDetails['jobInfo'][0]->job_title);  ?>" />
                                    <input type="hidden" name="from" value="<?php echo $this->internProfileInfo['internInfo'][0]->user_id; ?>" />
                                    <input type="hidden" name="to" value="<?php echo $this->jobDetails['jobInfo'][0]->employer_id; ?>" />
                                    <input type="hidden" name="job_id" value="<?php echo $this->jobDetails['jobInfo'][0]->job_id; ?>" />

                                    <label class="smalllabel darkgray lh22">From</label>
                                    <span class="green left lh22"><b><?php  echo $this->internProfileInfo['internInfo'][0]->first_name . ' '. $this->internProfileInfo['internInfo'][0]->last_name ?></b></span>
                                    <div class="clear"></div>
                                    <label class="smalllabel darkgray lh22">Subject</label>
                                    <span class="left lh22"><input type="text" class="required input" name="message_subject" value="Application: <?php echo $this->jobDetails['jobInfo'][0]->job_title; ?>"/></span>
                                    <div class="clear"></div>
                                    <label class="smalllabel darkgray lh22">Profile</label>
                                    <span class="green left lh22 small"><b>http://beta.urbaninterns.com/user/profile/profile-id/<?php echo $this->internProfileInfo['internInfo'][0]->user_id; ?></b></span>
                                    <div class="clear"></div>
                                    <textarea name="message_body" id="message_body" class="required bigtxt wid300 right">Write your application</textarea>
                                    <br />
                                    <span class="darkgray margin10"><b><input type="checkbox" checked name="save_job">&nbsp; Save Job</b></span>
                                    <br />
                                    <input type="submit" class="send_button left margin10" />

                                </form>

                            </div>

                    </div>

                    <div class="contact_box_bottom"></div>

                </div>
                <!-- end of right panel contact box -->


                <!-- start of right panel small box -->
                <div class="right_box">
                    <div class="right_box_top">
                            <div class="left_heading"> <img src="<?php echo $this->baseUrl().'/public/images/icon_star.png'?>" alt="Star" /> &nbsp;My Notes <span class="darkgray smallfont">(Only visible to you)</span></div>

                    </div>

                    <div class="right_box_middle">

                            <div class="right_box_content">
                                <form id="frm-note" action="<?php echo $this->baseUrl().'/user/message/save-user-note'; ?>" onsubmit="return saveUserNote();">
                                     <input type="hidden" name="job_id" value="<?php echo $this->jobDetails['jobInfo'][0]->job_id; ?>" />
                                     <input type="hidden" name="user_id" value="<?php echo $this->internProfileInfo['internInfo'][0]->user_id; ?>"  />

                                     <textarea name="note_text" id="note_text" class="required bigtxt">Write note... </textarea>
                                <br />
                                <input type="submit" class="save_button" />
                                </form>
                            </div>

                    </div>

                    <div class="right_box_bottom"></div>

                </div>
                <!-- end of right panel small box -->

                


                <!-- start of right panel small box -->
                <div class="right_box">
                    <div class="right_box_top">
                            <div class="left_heading"> <img src="<?php echo $this->baseUrl().'/public/images/icon_star.png' ?>" alt="Star" /> &nbsp;Share Job</div>

                    </div>

                    <div class="right_box_middle">

                            <div class="right_box_content">

                                <a href=""><img src="<?php echo $this->baseUrl().'/public/images/logo_twitter.png'?>" alt="share in twitter" class="imagelink"> <span class="green medium">Share on Twitter</span></a>
                                <br />
                                <a href=""><img src="<?php echo $this->baseUrl().'/public/images/logo_facebook.png'?>" alt="share in facebook" class="imagelink"> <span class="green medium">Share on Facebook</span></a>
                                <br />
                                <a href=""><img src="<?php echo $this->baseUrl().'/public/images/logo_linkedin.png'?>" alt="share in linkedin" class="imagelink"> <span class="green medium">Share on LinkedIn</span></a>
                                <br />
                                <a href=""><img src="<?php echo $this->baseUrl().'/public/images/logo_email.png'?>" alt="share via email" class="imagelink"> <span class="green medium">Share via Email</span></a>

                            </div>
                    </div>

                    <div class="right_box_bottom"></div>

                </div>
                <!-- end of right panel small box -->
                <br />

                <p class="green margin10"><b>FLAG THIS PAGE FOR OFFENSIVE CONTENT</b></p>

                <?php }

                else {

                ?>
                <div class="right_box">
                    <h3>You need to create profile apply to this job.</h3>
                </div>

                <?php  } ?>

              </div>

              <?php } ?>
              <!-- end of right panel -->


<?php
    }
    else
    {
        ?>

<h1 class="intern_header">
    No jobs found.
</h1>
<?php
    }
?>






