<?php
    isset ($this->errorMessage) ? print '<div class="errorDiv">'.$this->errorMessage.'</div>' : '';
    isset ($this->message)      ? print '<div class="messageDiv">'.$this->message.'</div>'    : '';
?>


<h1 class="intern_header">
   Reset you password
</h1>
<!-- start of left panel -->

<div class="registration_left">

    <div class="registration_left_top">
    </div>
    <div class="registration_left_middle">


        <div class="margin20">

<?php
echo $this->resetPasswordForm;
?>


            <div class="clear"></div>




        </div>


    </div>


    <div class="registration_left_bottom">
    </div>
</div>
<!-- end of left panel -->

<!-- start of right panel -->

<div class="registration_right">


</div>