 <h1 class="intern_header">
            About Urban Interns
            </h1>
        	<!-- start of left panel -->
        	
        	<div id="about_top">
                   <div class="left_heading"> <img src="<?php echo $this->baseUrl()?>/public/images/icon_star.png" alt="Star" /> &nbsp;Company</div>          
            </div>
                    
            <div id="about_middle">

            <div class="about_inner">
           
            <div class="about_image">
                <img src="<?php echo $this->baseUrl()?>/public/images/lauren_cari.png" alt="Lauren & Cari"  align="left"/>
            </div>
            
            <div class="about_text">
            Urban Interns is an online marketplace that connects high-growth companies with talented candidates looking for internships, part-time jobs, freelance work and contract positions. 
            <br /><br />
We offer all of the ease and efficiency of a full-service job board, with just one catch; if you're looking for full-time employment, you'll best be served elsewhere.
<br /><br />
Why? Because the way we work and staff is no longer focused on full-time. <br />
<ul class="greenli">
<li>Small businesses are growing quickly, but full-time help is often more (or more expensive) than what they need.</li> 
<li>Talented people are looking for flexible, part-time work to gain experience, increase their earnings, or both.</li> 
<li>Technology makes it easy to accomplish many tasks from anywhere, anytime.</li>
</ul>
UrbanInterns was created to meet the needs of the new job market. The world of work is no longer just "another day at the office."
<br /><br />
Interested? Check out <a href='<?php echo $this->baseUrl()?>/w/page/how-it-works/' class="green">How it Works</a> to get started.
            </div>
                 

            <br />
            <br />
            <center>
                <img src="<?php echo $this->baseUrl()?>/public/images/timeline.png" alt="Timeline" />
            </center>
            <br />
            <br />
            
            <div class="left_heading"> <img src="<?php echo $this->baseUrl()?>/public/images/icon_star.png" alt="Star" /> &nbsp;Meet Our Management Team</div> 
            <div class="clear"></div>
            <div class="bigline"></div>
            
                    
            <div class="about_image">
                <img src="<?php echo $this->baseUrl()?>/public/images/lauren.png" alt="Lauren"  align="left"/>
            </div>
            <div class="about_text">
            <b>Lauren Porat</b><br />
Lauren is an enthusiastic executive with experience in both big firms and startups.  Her main focus as co-founder of Urban Interns is on product and finance, so if you have suggestions or feedback on the site, email her <a href='mailto:feedback@urbaninterns.com' class="nodec">here!</a>
<br /><br />
Prior to starting Urban Interns, Lauren spent 8 years at IAC in various strategy and finance roles. Most recently, as VP of Strategic Planning, she was responsible for best practice sharing, marketing and product development opportunities across IAC's multiple business units. She spent 3.5 years in Investor Relations, learning the ins and outs of the public investment community. Prior to that, she did M&A, helping IAC grow from what was at the time USA Networks to a true diversified internet company by acquiring companies such as Expedia. IAC, while a huge company, was where Lauren got the startup bug, as sitting in the corporate office she worked hands on every day with amazing entrepreneurs. 
<br /><br />
Before IAC, Lauren worked at Oaktree Capital Management doing private equity. She started her career at Merrill Lynch in the media investment banking group, focusing mainly on M&A but also working on high profile public deals like the Fox Entertainment Group's IPO. 
<br /><br />
Lauren lives in Larchmont, NY with her husband Sam and 2 young boys.
<br /><br />
<a href="" class="greenbold"><img src="<?php echo $this->baseUrl()?>/public/images/linkedin_small.png" alt="Linked In" align="absmiddle"/> &nbsp;Connect with Lauren on LinkedIn</a>
            </div>
            <div class="clear"></div>
            <br />
            <div class="clear"></div>
            <div class="about_image">
                <img src="<?php echo $this->baseUrl()?>/public/images/cari.png" alt="Cari"  align="left"/>
            </div>
            <div class="about_text">
            <b>Cari Sommer</b><br />
As Co-Founder of Urban Interns, Cari focuses primarily on business strategy, marketing and business development.  She also manages the company's public relations. In short, Cari spends her time trying to convince anyone and everyone that  Urban Interns is a need-to-know resource for growing companies and job seekers.
<br /><br />
Cari first perfected this Art of Advocacy during the seven years she practiced law.  She began her legal career at the international law firms of Cadwalader Wickersham and Taft, and later Bryan Cave, where she focused primarily on commercial, bankruptcy and securities litigation.  After leaving Bryan Cave and before starting Urban Interns, Cari was the Director of Business Development for Lexolution, a national legal staffing firm.  Her career transition from practicing law to becoming an entrepreneur has been chronicled by the Wall Street Journal, Above the Law (and Super Women JD—this hasn't come out yet, if it doesn't by site launch, reminder to self to scratch it).
<br /><br /> 
Throughout her career, Cari has also been deeply committed to community philanthropy.  From 2006-2009, she served as the Chair of the New York Board of Directors of Step Up Women's Network, a national nonprofit dedicated to strengthening community resources for women and girls. During her time as Chair, Step Up's membership increased by 400 percent and the fundraising doubled. Cari remains an active Board member of Step Up. 
<br /><br />
Cari is a graduate of Cornell University and Brooklyn Law.  She lives in NYC with her husband and son.
<br /><br />
<a href="" class="greenbold"><img src="<?php echo $this->baseUrl()?>/public/images/linkedin_small.png" alt="Linked In" align="absmiddle"/> &nbsp; Connect with Cari on LinkedIn</a>
            </div>
            
            
            <div class="clear"></div>
            <br />
            <div class="clear"></div>
            
            <div class="left_heading"> <img src="<?php echo $this->baseUrl()?>/public/images/icon_star.png" alt="Star" /> &nbsp;Meet Our Advisory Board</div> 
            <div class="clear"></div>
            <div class="bigline"></div>
            
            <div class="fullpagetext">
            
            <b>Marc Ferrentino</b><br />
Marc Ferrentino is the Chief Technical Architect for Salesforce.com. Marc joined Salesforce.com in February 2007. His responsibilities included early stage product development and marketing, evangelism of the Force.com platform, and promoting Salesforce.com's open source initiatives. Mr. Ferrentino is also involved with developing Salesforce.com's Collaboration and Platform strategic direction. 
<br /><br />
Prior to Salesforce.com, Marc served as the Vice President of Engineering at Vettro Corp, a global leader in mobile on-demand applications. There, Marc was responsible for the development and launch of Vettro's applications and was the creative force behind Vettro's core technology. Prior to Vettro, Marc worked as Vice President of Development at InternetCash.com where he was instrumental in developing a prepaid spending card for the Internet and a real-time transaction network. Over the course of his career, Mr. Ferrentino has held technology positions at Goldman Sachs and Westinghouse/Cutler-Hammer. 
<br /><br />
Marc holds a Bachelor of Science degree in Electrical Engineering from the University of Michigan and has participated in the Masters of Statistics with a Concentration in Finance program at Columbia University.
<br /><br />
<b>Shana Fisher</b><br />
Shana Fisher is the Senior Vice President of Mergers & Acquisitions and Strategy at IAC, where oversees all aspects of strategy and certain specific areas of M&A activity. She's also responsible for IAC's effects with Instant Action, the company's soon-to-be launched online gaming site. From December 2003 to January 2005 Shana served as IAC's Senior Vice President, Strategic Planning, and prior to that as the Senior Vice President of Business Operations for IAC. 
<br /><br />
Previously, Shana served as Vice President and Director, Media and Technology Mergers and Acquisitions and Corporate Finance for Allen & Company, LLC. While there, she led principle investments and advised publicly traded technology firms, private telecommunications firms and media companies. Prior to Allen & Company, LLC., Shana was a program manager for the Microsoft Corporation and prior to that she was a software developer for I | O 360 Consulting. 
<br /><br />
Shana received her B.A. from Hampshire College with a triple major in Sculpture, Philosophy and Linguistics and attended the Master of Arts and Sciences program at New York University.
<br /><br />
<b>Emily Hickey</b><br />
Emily has been doing Product Marketing for internet start-ups for over 10 years in New York City and Silicon Valley. She currently works as the Chief Marketing Officer for Tracked.com, a new business information and networking site based out of NYC. 
<br /><br />
She has previously served as the VP of Products at HotJobs.com, which sold to Yahoo! in 2002; the Chief Operating Officer of PhotoShelter, a profitable General Catalyst funded software company in NYC; and the Assistant Executive Director of WildAid, a San Francisco-based NGO dedicated to stopping the endangered species trade. 
<br /><br />
She holds a BA from the University of North Carolina, Chapel Hill, and an MS from Stanford Business School, where she was a Sloane Fellow. 
<br />         
            </div>
            
            </div>                  
            
            </div>

                       
            <div id="about_bottom">
            
            </div>
        	