            <h1 class="intern_header">
            How It Works
            </h1>
        	<!-- start of left panel -->
        	
                <img src="<?php echo $this->baseUrl()?>/public/images/howitworks.png" alt="How it works" style="margin:5px"/>
            
        	
        	<div class="clear"></div>
        	
        	<div id="about_top">
                   <div class="left_heading"> <img src="<?php echo $this->baseUrl()?>/public/images/icon_star.png" alt="Star" /> &nbsp;So, what is it?</div>          
            </div>
                    
            <div id="about_middle">

            <div class="about_inner_one">
           
            
            Urban Interns is about making the right connections—fast. Our online marketplace allows employers and talent to post their information, find the right match, and connect quickly and easily. 
            <br /><br />
Urban Interns offers ongoing subscriptions for lasting value. Employers can maintain ongoing connections with a roster of potential candidates and manage a robust talent pipeline, while job seekers can stay on top of the market.
<br /><br />
<b>What Urban Interns is Not</b><br />
Urban Interns is not a recruiting or staffing agency. Like most job boards, once you've found the right talent or gig—the rest is up to you. All application, hiring, and compensation discussions take place directly between employers and job seekers. Along the way, we'll offer tools and tips to make the process run smoothly.


            <div class="clear"></div>
            <div class="bigline_one"></div>
            
        
            <div class="split_one">
            
            <span class="biglabel">For Employers</span>
            <div class="clear"></div>
            <br />
            <div class="clear"></div>
<b>Post a Job</b><br />
<b>Every level of membership comes with at least 1 job posting,</b> which will be active for 30 days. Higher levels of membership allow you to add multiple listings. 
<a href='<?php echo $this->baseUrl()?>/registration/account/post-job' class="green">Check out our membership options.</a>
<br /><br />
<b>Search Urban Interns</b><br />
Membership also comes with access to our talent database for 30 days. We've given you the tools to slice and dice our database by availability, skills, industry, and location. 
<a href='<?php echo $this->baseUrl()?>/search/intern' class="green">Take a look at these great candidates. </a>
<br /><br />
<b>Connect</b><br />
When you find a candidate that you like, send them a message. You can also reply to applications that appeal to you. Remember, from there, you control the interaction and next steps to making the hire. 
<br />
<br />

<a href='<?php echo $this->baseUrl()?>/registration/account/post-job'><img src='<?php echo $this->baseUrl()?>/public/images/button_getstarted.png' alt='Get Started' /></a>
<br />
<br /> 
<br />
Employers have had success with Urban Interns! <a href='<?php echo $this->baseUrl()?>/blog/employers' class="green">Read their Stories</a>
            
            </div>
            
            <div class="split_two">
            
            
            <span class="biglabel">For Job Seekers</span>

<div class="clear"></div>
            <br />
            <div class="clear"></div>
<b>Post Your Profile</b><br />
Joining Urban Interns is free. You can search jobs, as well as post your profile to be found by employers. Want more visibility? Upgrade your membership to highlight your profile in search results. 
<a href='<?php echo $this->baseUrl()?>/registration/account/apply-job' class="green">Check out our membership options.</a>
<br /><br />
<b>Find a Job</b><br />
Don't wait for employers to find you. Membership gives you complete access to our jobs database. Search by keyword, or slice and dice the listings by your schedule, skills, industry, and location. 
<a href='<?php echo $this->baseUrl()?>/search/job' class="green">Take a look at these great jobs.</a>
<br /><br />
<b>Apply</b><br />
There are a lot of cool, growing companies out there with great jobs. Once you've found one you like, apply. With your application, employers will see your profile, as well as your personal message, telling them why you're perfect for the job.
<br />
<br />

<a href='<?php echo $this->baseUrl()?>/registration/account/apply-job'><img src='<?php echo $this->baseUrl()?>/public/images/button_getstarted.png' alt='Get Started' /></a>
 
<br />
<br />
<br />
Job seekers have had success with Urban Interns! <a href='<?php echo $this->baseUrl()?>/blog/jobseekers' class="green">Read their Stories</a>

            
            </div>
            

            
            
            
            </div>                  
            
            </div>

                       
            <div id="about_bottom">
            
            </div>