<script type="text/javascript">

    function chkInput()
    {
        var keyword, location_name;

        if($('.job_search_input').val() == 'jobs' && $('.big_select').val() == '')
        {
            window.location = "<?php echo $this->baseUrl().'/search/job/job-search-results/?keyword=&location_name='; ?>";
        }
        else
        {
            if($('.job_search_input').val() == 'jobs')
                keyword = '';
            else
                keyword = $('.job_search_input').val();

            location_name = $('.big_select').val();

            window.location = "<?php echo $this->baseUrl().'/search/job/job-search-results/?keyword='?>" + keyword + "&location_name=" + location_name;
        };
    }

</script>

<h1 class="intern_header">
    Find A Job
</h1>
<!-- start of left panel -->

<div class="panel_left">

    <!-- start keywords box -->

    <div class="find_job_box">
        <div class="find_job_box_top"></div>
        <div class="find_job_box_middle">

            <ul class="nobullet">
                <li class="topmargin7">Search for</li>
                <form onsubmit="return false;" action="<?php echo $this->baseUrl() . '/search/job/job-search-results' ?>" method="get">
                
                <li><input type="text" name="keyword" class="job_search_input" onblur="if (value== '') {value='jobs'}" onfocus="if (value == 'jobs') {value=''}" value="jobs" /></li>
                <li class="topmargin7">in</li>
                <li>
                    <select class="big_select" name="location_name" id="search_in">
                        <option value="">Any City</option>
                       
                        <?php
                             foreach ($this->location as $value) {
                                echo "<option value='{$value->location_name}'>".ucwords($value->location_name)."</option>";
                            }
                        ?>

                    </select>
                </li>
                <li>
                    <input onclick="chkInput();" type="submit" class="job_search_big" />
                </li>
                </form>
            </ul>






        </div>
        <div class="find_job_box_bottom"></div>
    </div>

    <!-- end keywords box -->


    <!-- start featured intern box -->

    <div class="featured_box">
        <div class="featured_box_top">
            <div class="left_heading"> <img src="<?php echo $this->baseUrl().'/public/images/icon_star.png'?>" alt="Star" /> &nbsp;Browse Jobs</div>
        </div>

        <div class="featured_box_middle">


            <ul class="keywords">
                <li class="keywords_header">By Skills</li>
                <?php
                    foreach ($this->skills as $value) {
                        echo "<li><a href='{$this->baseUrl()}/search/job/job-search-results/?skill={$value->skill_name}'>". ucwords($value->skill_name)."</a></li>";
                    }
                ?>

            </ul>

            <ul class="keywords">
                <li class="keywords_header">By Industry</li>
                <?php
                     foreach ($this->industry as $value) {
                        echo "<li><a href='{$this->baseUrl()}/search/job/job-search-results/?industry/{$value->industry_name}'>".ucwords($value->industry_name)."</a></li>";
                    }
                ?>

            </ul>

            <ul class="keywords">
                <li class="keywords_header">By Availability</li>
               <?php
                    foreach ($this->availablity as $value) {
                        echo "<li><a href='{$this->baseUrl()}/search/job/job-search-results/?seasons={$value->title}'>".ucwords($value->title)."</a></li>";
                    }
                ?>

            </ul>

            <ul class="keywords noborder">
                <li class="keywords_header">By Location</li>
                <?php
                     foreach ($this->location as $value) {
                        echo "<li><a href='{$this->baseUrl()}/search/job/job-search-results/?location_name={$value->location_name}'>".ucwords($value->location_name)."</a></li>";
                    }
                ?>

            </ul>


        </div>

        <div class="featured_box_bottom">
        </div>

    </div>


    <!-- end featured intern box -->

</div>
<!-- end of left panel -->

<!-- start of right panel -->

<div class="panel_right">

    <!-- start of right panel small box -->
    <div class="right_box">
        <div class="right_box_top">
            <div class="left_heading"> <img src="<?php echo $this->baseUrl().'/public/images/icon_star.png'?>" alt="Star" /> &nbsp;My Job Alerts / Saved Searches </div>
        </div>

        <div class="right_box_middle">

            <table class="tbl_small" cellpadding="0" cellspacing="0">
                <tr>
                    <td>Summer Interns</td>
                    <td><b>2 New Matches</b></td>
                    <td><img src="<?php echo $this->baseUrl().'/public/images/delete.png'?>" alt="delete" /></td>
                </tr>
                <tr>
                    <td>Summer Interns</td>
                    <td><b>2 New Matches</b></td>
                    <td><img src="<?php echo $this->baseUrl().'/public/images/delete.png'?>" alt="delete" /></td>
                </tr>
                <tr>
                    <td>Summer Interns</td>
                    <td>No New Matches</td>
                    <td><img src="<?php echo $this->baseUrl().'/public/images/delete.png'?>" alt="delete" /></td>
                </tr>
                <tr>
                    <td colspan="3">
                        <br />
                        Send alert <select class="select" name="send_alert" id="send_alert">
                            <option> As soon as job is posted</option>
                        </select>
                        <br /> <br />
                    </td>
                </tr>
                <tr>
                    <td colspan="3" class="noborder">
                        <ul class="basic_list">
                            <li class="keywords_header">New Matches</li>
                            <li> Dhaka </li>
                            <li> Dhaka </li>
                            <li> Dhaka </li>
                            <li> Dhaka </li>
                        </ul>
                    </td>
                </tr>
            </table>


        </div>

        <div class="right_box_bottom"></div>

    </div>
    <!-- end of right panel small box -->


    <!-- start of right panel small box -->
    <div class="right_box">
        <div class="right_box_top">
            <div class="left_heading"> <img src="<?php echo $this->baseUrl().'/public/images/icon_star.png'?>" alt="Star" /> &nbsp;Saved Jobs</div>

            <div class="green_links right"><a href="">ALL ACTIVE JOBS ></a></div>
        </div>

        <div class="right_box_middle">

            <div class="right_box_content">

                <ul class="folder_list">
                    <li> <b>Paid Internship at Boutique Investment Firm</b>
                        <br />
                        <img src="<?php echo $this->baseUrl().'/public/images/sticky.png'?>" alt="note" /> <span class="darkgray">Applied 5/28, Very low stipend</span>
                    </li>
                    <li> <b>Paid Internship at Boutique Investment Firm</b>
                        <br />
                        <img src="<?php echo $this->baseUrl().'/public/images/sticky.png'?>" alt="note" /> <span class="darkgray">Applied 5/28, Very low stipend</span>
                    </li>
                    <li> <b>Paid Internship at Boutique Investment Firm</b>
                        <br />
                        <img src="<?php echo $this->baseUrl().'/public/images/sticky.png'?>" alt="note" /> <span class="darkgray">Applied 5/28, Very low stipend</span>
                    </li>
                    <li> <b>Paid Internship at Boutique Investment Firm</b>
                        <br />
                        <img src="<?php echo $this->baseUrl().'/public/images/sticky.png'?>" alt="note" /> <span class="darkgray">Applied 5/28, Very low stipend</span>
                    </li>
                </ul>

            </div>

        </div>

        <div class="right_box_bottom"></div>

    </div>
    <!-- end of right panel small box -->


</div>

<!-- end of right panel -->